// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type NewEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEventRequest) Reset()         { *m = NewEventRequest{} }
func (m *NewEventRequest) String() string { return proto.CompactTextString(m) }
func (*NewEventRequest) ProtoMessage()    {}
func (*NewEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *NewEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEventRequest.Unmarshal(m, b)
}
func (m *NewEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEventRequest.Marshal(b, m, deterministic)
}
func (m *NewEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEventRequest.Merge(m, src)
}
func (m *NewEventRequest) XXX_Size() int {
	return xxx_messageInfo_NewEventRequest.Size(m)
}
func (m *NewEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewEventRequest proto.InternalMessageInfo

func (m *NewEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type NewEventResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEventResponse) Reset()         { *m = NewEventResponse{} }
func (m *NewEventResponse) String() string { return proto.CompactTextString(m) }
func (*NewEventResponse) ProtoMessage()    {}
func (*NewEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *NewEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEventResponse.Unmarshal(m, b)
}
func (m *NewEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEventResponse.Marshal(b, m, deterministic)
}
func (m *NewEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEventResponse.Merge(m, src)
}
func (m *NewEventResponse) XXX_Size() int {
	return xxx_messageInfo_NewEventResponse.Size(m)
}
func (m *NewEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewEventResponse proto.InternalMessageInfo

func (m *NewEventResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ModifyEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyEventRequest) Reset()         { *m = ModifyEventRequest{} }
func (m *ModifyEventRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyEventRequest) ProtoMessage()    {}
func (*ModifyEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *ModifyEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyEventRequest.Unmarshal(m, b)
}
func (m *ModifyEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyEventRequest.Marshal(b, m, deterministic)
}
func (m *ModifyEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyEventRequest.Merge(m, src)
}
func (m *ModifyEventRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyEventRequest.Size(m)
}
func (m *ModifyEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyEventRequest proto.InternalMessageInfo

func (m *ModifyEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ModifyEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type ModifyEventResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyEventResponse) Reset()         { *m = ModifyEventResponse{} }
func (m *ModifyEventResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyEventResponse) ProtoMessage()    {}
func (*ModifyEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *ModifyEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyEventResponse.Unmarshal(m, b)
}
func (m *ModifyEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyEventResponse.Marshal(b, m, deterministic)
}
func (m *ModifyEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyEventResponse.Merge(m, src)
}
func (m *ModifyEventResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyEventResponse.Size(m)
}
func (m *ModifyEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyEventResponse proto.InternalMessageInfo

func (m *ModifyEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RemoveEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEventRequest) Reset()         { *m = RemoveEventRequest{} }
func (m *RemoveEventRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEventRequest) ProtoMessage()    {}
func (*RemoveEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *RemoveEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEventRequest.Unmarshal(m, b)
}
func (m *RemoveEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEventRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEventRequest.Merge(m, src)
}
func (m *RemoveEventRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEventRequest.Size(m)
}
func (m *RemoveEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEventRequest proto.InternalMessageInfo

func (m *RemoveEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveEventResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEventResponse) Reset()         { *m = RemoveEventResponse{} }
func (m *RemoveEventResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveEventResponse) ProtoMessage()    {}
func (*RemoveEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *RemoveEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEventResponse.Unmarshal(m, b)
}
func (m *RemoveEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEventResponse.Marshal(b, m, deterministic)
}
func (m *RemoveEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEventResponse.Merge(m, src)
}
func (m *RemoveEventResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveEventResponse.Size(m)
}
func (m *RemoveEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEventResponse proto.InternalMessageInfo

func (m *RemoveEventResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetEventRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventRequest) Reset()         { *m = GetEventRequest{} }
func (m *GetEventRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventRequest) ProtoMessage()    {}
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{7}
}

func (m *GetEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRequest.Unmarshal(m, b)
}
func (m *GetEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRequest.Marshal(b, m, deterministic)
}
func (m *GetEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRequest.Merge(m, src)
}
func (m *GetEventRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventRequest.Size(m)
}
func (m *GetEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRequest proto.InternalMessageInfo

func (m *GetEventRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEventResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventResponse) Reset()         { *m = GetEventResponse{} }
func (m *GetEventResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventResponse) ProtoMessage()    {}
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{8}
}

func (m *GetEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventResponse.Unmarshal(m, b)
}
func (m *GetEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventResponse.Marshal(b, m, deterministic)
}
func (m *GetEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventResponse.Merge(m, src)
}
func (m *GetEventResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventResponse.Size(m)
}
func (m *GetEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventResponse proto.InternalMessageInfo

func (m *GetEventResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *GetEventResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*NewEventRequest)(nil), "calendar.NewEventRequest")
	proto.RegisterType((*NewEventResponse)(nil), "calendar.NewEventResponse")
	proto.RegisterType((*ModifyEventRequest)(nil), "calendar.ModifyEventRequest")
	proto.RegisterType((*ModifyEventResponse)(nil), "calendar.ModifyEventResponse")
	proto.RegisterType((*RemoveEventRequest)(nil), "calendar.RemoveEventRequest")
	proto.RegisterType((*RemoveEventResponse)(nil), "calendar.RemoveEventResponse")
	proto.RegisterType((*GetEventRequest)(nil), "calendar.GetEventRequest")
	proto.RegisterType((*GetEventResponse)(nil), "calendar.GetEventResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6b, 0xdb, 0x40,
	0x10, 0xc5, 0x91, 0x5a, 0xb5, 0xea, 0x08, 0x2a, 0xb3, 0xf6, 0x41, 0x16, 0xfd, 0xe3, 0x2e, 0x35,
	0x18, 0x0a, 0x72, 0x71, 0x29, 0xf4, 0xea, 0xb6, 0x21, 0x24, 0x21, 0x39, 0x28, 0x39, 0xe5, 0xa6,
	0x58, 0x63, 0xb3, 0xd8, 0xd6, 0x2a, 0xab, 0xb5, 0x43, 0xbe, 0x51, 0x6e, 0xf9, 0x8a, 0xc1, 0xbb,
	0xda, 0x48, 0x96, 0x1d, 0x93, 0x93, 0xd8, 0x9d, 0xdf, 0xbc, 0x37, 0xf3, 0x56, 0x00, 0x12, 0x0b,
	0x19, 0xe5, 0x82, 0x4b, 0x4e, 0xdc, 0x49, 0xb2, 0xc0, 0x2c, 0x4d, 0x44, 0xf8, 0x75, 0xc6, 0xf9,
	0x6c, 0x81, 0x43, 0x75, 0x7f, 0xb3, 0x9a, 0x0e, 0x25, 0x5b, 0x62, 0x21, 0x93, 0x65, 0xae, 0xd1,
	0xf0, 0x4b, 0x13, 0x48, 0x57, 0x22, 0x91, 0x8c, 0x67, 0xba, 0x4e, 0x1f, 0x2c, 0x70, 0x8e, 0xd6,
	0x98, 0x49, 0xd2, 0x01, 0x47, 0x32, 0xb9, 0xc0, 0xc0, 0xea, 0x59, 0x83, 0x0f, 0xb1, 0x3e, 0x90,
	0x1e, 0x78, 0x29, 0x16, 0x13, 0xc1, 0xf2, 0x4d, 0x53, 0x60, 0xab, 0x5a, 0xfd, 0x8a, 0xfc, 0x04,
	0xa7, 0x90, 0x89, 0x90, 0xc1, 0x9b, 0x9e, 0x35, 0xf0, 0x46, 0x61, 0xa4, 0x1d, 0x23, 0xe3, 0x18,
	0x5d, 0x99, 0x91, 0x62, 0x0d, 0x92, 0xdf, 0xe0, 0x9a, 0x29, 0x82, 0xb7, 0xaa, 0xa9, 0xbb, 0xd3,
	0xf4, 0xbf, 0x04, 0xe2, 0x67, 0x94, 0xfe, 0x01, 0xff, 0x02, 0xef, 0xd4, 0xb0, 0x31, 0xde, 0xae,
	0xb0, 0x90, 0xa4, 0x0f, 0x0e, 0x6e, 0xce, 0x6a, 0x66, 0x6f, 0xe4, 0x47, 0x26, 0x98, 0x48, 0x63,
	0xba, 0x4a, 0x29, 0xb4, 0xaa, 0xce, 0x22, 0xe7, 0x59, 0x81, 0xe4, 0x23, 0xd8, 0x2c, 0x2d, 0x77,
	0xb5, 0x59, 0x4a, 0xcf, 0x80, 0x9c, 0xf3, 0x94, 0x4d, 0xef, 0xb7, 0x0c, 0x1a, 0x54, 0x65, 0x68,
	0x1f, 0x34, 0xfc, 0x01, 0xed, 0x2d, 0xb1, 0xd2, 0xb3, 0x03, 0x0e, 0x0a, 0xc1, 0x85, 0x89, 0x58,
	0x1d, 0xe8, 0x77, 0x20, 0x31, 0x2e, 0xf9, 0x1a, 0x0f, 0x39, 0xd3, 0x3e, 0xb4, 0xb7, 0xa8, 0x6a,
	0x0d, 0x3e, 0x57, 0x98, 0x1b, 0xdb, 0x7c, 0x4e, 0xbf, 0x81, 0x7f, 0x8c, 0xf2, 0xa0, 0xd2, 0x09,
	0xb4, 0x2a, 0xa4, 0x94, 0x79, 0x5d, 0x90, 0xa5, 0x9b, 0x6d, 0xdc, 0x46, 0x8f, 0x36, 0xf8, 0xff,
	0x4a, 0xf2, 0x12, 0xc5, 0x9a, 0x4d, 0x90, 0x8c, 0xc1, 0x35, 0x61, 0x93, 0x6e, 0xa5, 0xd3, 0x78,
	0xba, 0x30, 0xdc, 0x57, 0x2a, 0xa7, 0x39, 0x05, 0xaf, 0x16, 0x1f, 0xf9, 0x54, 0xa1, 0xbb, 0x4f,
	0x14, 0x7e, 0x7e, 0xa1, 0x5a, 0x69, 0xd5, 0x72, 0xab, 0x6b, 0xed, 0x86, 0x5e, 0xd7, 0xda, 0x17,
	0xf6, 0x18, 0x5c, 0x93, 0x5c, 0x7d, 0xb5, 0x46, 0xe0, 0xf5, 0xd5, 0x9a, 0x41, 0xff, 0x7d, 0x7f,
	0xed, 0xe8, 0x7f, 0xfc, 0x9d, 0xfa, 0xfc, 0x7a, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x40, 0x1a,
	0x0d, 0xd8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalendarServiceClient is the client API for CalendarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarServiceClient interface {
	NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*NewEventResponse, error)
	ModifyEvent(ctx context.Context, in *ModifyEventRequest, opts ...grpc.CallOption) (*ModifyEventResponse, error)
	RemoveEvent(ctx context.Context, in *RemoveEventRequest, opts ...grpc.CallOption) (*RemoveEventResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
}

type calendarServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalendarServiceClient(cc *grpc.ClientConn) CalendarServiceClient {
	return &calendarServiceClient{cc}
}

func (c *calendarServiceClient) NewEvent(ctx context.Context, in *NewEventRequest, opts ...grpc.CallOption) (*NewEventResponse, error) {
	out := new(NewEventResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarService/NewEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ModifyEvent(ctx context.Context, in *ModifyEventRequest, opts ...grpc.CallOption) (*ModifyEventResponse, error) {
	out := new(ModifyEventResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarService/ModifyEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) RemoveEvent(ctx context.Context, in *RemoveEventRequest, opts ...grpc.CallOption) (*RemoveEventResponse, error) {
	out := new(RemoveEventResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarService/RemoveEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarService/GetEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServiceServer is the server API for CalendarService service.
type CalendarServiceServer interface {
	NewEvent(context.Context, *NewEventRequest) (*NewEventResponse, error)
	ModifyEvent(context.Context, *ModifyEventRequest) (*ModifyEventResponse, error)
	RemoveEvent(context.Context, *RemoveEventRequest) (*RemoveEventResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
}

// UnimplementedCalendarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarServiceServer struct {
}

func (*UnimplementedCalendarServiceServer) NewEvent(ctx context.Context, req *NewEventRequest) (*NewEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewEvent not implemented")
}
func (*UnimplementedCalendarServiceServer) ModifyEvent(ctx context.Context, req *ModifyEventRequest) (*ModifyEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyEvent not implemented")
}
func (*UnimplementedCalendarServiceServer) RemoveEvent(ctx context.Context, req *RemoveEventRequest) (*RemoveEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEvent not implemented")
}
func (*UnimplementedCalendarServiceServer) GetEvent(ctx context.Context, req *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}

func RegisterCalendarServiceServer(s *grpc.Server, srv CalendarServiceServer) {
	s.RegisterService(&_CalendarService_serviceDesc, srv)
}

func _CalendarService_NewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).NewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarService/NewEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).NewEvent(ctx, req.(*NewEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ModifyEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ModifyEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarService/ModifyEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ModifyEvent(ctx, req.(*ModifyEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_RemoveEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).RemoveEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarService/RemoveEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).RemoveEvent(ctx, req.(*RemoveEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarService/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalendarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.CalendarService",
	HandlerType: (*CalendarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewEvent",
			Handler:    _CalendarService_NewEvent_Handler,
		},
		{
			MethodName: "ModifyEvent",
			Handler:    _CalendarService_ModifyEvent_Handler,
		},
		{
			MethodName: "RemoveEvent",
			Handler:    _CalendarService_RemoveEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _CalendarService_GetEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
